name: dynamite_petstore_example
description: An example showing how to use dynamite for the Petstore example API.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.9.0
  dynamite_runtime: ^0.4.0
  http: ^1.2.1
  meta: ^1.0.0
  uri: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.11
  built_value_generator: ^8.9.2
  dynamite: ^0.4.0
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
