name: neon_news
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0
  flutter: ^3.22.0

dependencies:
  built_collection: ^5.0.0
  collection: ^1.0.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  go_router: ^14.0.0
  html: ^0.15.0
  intl: ^0.19.0
  logging: ^1.0.0
  neon_framework:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_framework
  nextcloud: ^6.1.0
  rxdart: ^0.27.0
  share_plus: ^9.0.0
  timezone: ^0.9.4
  url_launcher: ^6.0.0
  wakelock_plus: ^1.0.0
  webview_flutter: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  go_router_builder: ^2.7.0
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  vector_graphics_compiler: ^1.1.11+1

flutter:
  uses-material-design: true
  assets:
    - assets/
