name: app
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0
  flutter: ^3.22.0

dependencies:
  built_collection: ^5.0.0
  flutter:
    sdk: flutter
  neon_dashboard:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon_dashboard
  neon_files:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon_files
  neon_framework:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_framework
  neon_news:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon_news
  neon_notes:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon_notes
  neon_notifications:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon_notifications
  neon_talk:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon_talk
  vector_graphics: any

dev_dependencies:
  custom_lint: ^0.6.4
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  vector_graphics_compiler: any

flutter:
  uses-material-design: true
  assets:
    - assets/
