name: cookie_store
description: A RFC compliant cookie_jar alternative
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  cookie_jar: ^4.0.0
  meta: ^1.0.0
  timezone: ^0.9.4
  universal_io: ^2.0.0

dev_dependencies:
  cookie_store_conformance_tests:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/cookie_store_conformance_tests
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  test: ^1.25.7
