name: neon_framework
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0
  flutter: ^3.22.0

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.9.0
  collection: ^1.0.0
  cookie_jar: ^4.0.0
  cookie_store:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/cookie_store
  crypto: ^3.0.0
  crypton: ^2.0.0
  cupertino_icons: ^1.0.0 # Do not remove this, is it needed on iOS/macOS. It will not include icons on other platforms because Apple forbids it.
  dynamic_color: ^1.0.0
  dynamite_runtime: ^0.4.0
  emoji_picker_flutter: ^2.0.0
  file_picker: ^8.0.0+1
  filesize: ^2.0.0
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.8.2
  flutter_local_notifications: ^17.0.0
  flutter_localizations:
    sdk: flutter
  flutter_material_design_icons: ^1.0.0
  flutter_native_splash: ^2.0.0
  flutter_svg: ^2.0.0
  flutter_zxing: ^1.0.0
  go_router: ^14.0.0
  http: ^1.0.0
  image: ^4.0.0
  intersperse: ^2.0.0
  intl: ^0.19.0
  logging: ^1.0.0
  meta: ^1.0.0
  nextcloud: ^6.1.0
  package_info_plus: ^8.0.0
  path: ^1.0.0
  path_provider: ^2.1.0
  permission_handler: ^11.0.0
  provider: ^6.0.0
  quick_actions: ^1.0.0
  rxdart: ^0.27.4
  scrollable_positioned_list: ^0.3.0
  shared_preferences_platform_interface: ^2.3.2
  sort_box:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/sort_box
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2
  sqflite_common_ffi_web: ^0.4.2+3
  timezone: ^0.9.4
  unifiedpush: ^5.0.0
  unifiedpush_android: ^2.0.0
  universal_io: ^2.0.0
  url_launcher: ^6.1.0
  vector_graphics: ^1.0.0
  web: ^0.5.0
  window_manager: ^0.3.0
  xml: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.11
  built_value_generator: ^8.9.2
  cookie_store_conformance_tests:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/cookie_store_conformance_tests
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.0
  mocktail: ^1.0.4
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  shared_preferences: ^2.2.3
  vector_graphics_compiler: ^1.1.11+1
  version: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/server/
  plugin:
    platforms:
      linux:
        dartPluginClass: LinuxNeonPlatform
      android:
        dartPluginClass: AndroidNeonPlatform
      web:
        pluginClass: WebNeonPlatform
        fileName: src/platform/web.dart
