name: 'Update test presets'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
      - name: Install dart
        uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672 # v1
      - name: Setup
        run: ./tool/setup.sh

      - name: Update presets
        run: ./tool/generate-nextcloud-test-presets.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6
        with:
          commit-message: "chore(nextcloud_test): Update presets"
          signoff: true
          branch: chore/nextcloud_test/update-presets
          delete-branch: true
          title: "chore(nextcloud_test): Update presets"
          body: ""
